jwt:
  secret: ${JWT_SECRET_KEY}
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
spring:
  mail:
    host: smtpout.secureserver.net
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google: ${GOOGLE_CLIENT_ID}
  jackson:
    time-zone: UTC
  ai:
    openai:
      chat:
        options:
          model: gpt-4.1
      api-key: ${OPENAI_API_KEY}
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages
  application:
    name: recoverAiBackend
  datasource:
    url: jdbc:postgresql://${DB_HOST:vitaloop.app}:${DB_PORT:5432}/${DB_NAME:vitaloop}
    username: ${DB_USERNAME:vitaloop-admin}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      auto-commit: true
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    open-in-view: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
          dataSource:
            quartzDataSource:
              URL: jdbc:postgresql://${DB_HOST:vitaloop.app}:${DB_PORT:5432}/${DB_NAME:vitaloop}
              driver: org.postgresql.Driver
              user: ${DB_USERNAME:vitaloop-admin}
              password: ${DB_PASSWORD}
              provider: hikaricp
          jobStore:
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            tablePrefix: QRTZ_
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
